[[acpi-props]]
=== RVI-specific ACPI Device Properties

This section is used to define the `_DSD` device properties cite:[DSD] in the `rscv-` namespace.

Where explicit values are provided in a property definition, only these values must be used. System behavior with any other values is undefined.

[width=100%]
[%header, cols="10,5,25"]
|===
|  Property  ^| Type | Description
3+|_Currently, there are no properties defined in the `rscv-` namespace. Request for new property names in the `rscv-` namespace should be made as a git pull request to this table._
|===


[[acpi-props-uart]]
=== ACPI Device Properties for UART Devices
Generic 16550-compatible UART devices can have device properties in the global name space
since Operating Systems are already using them.

[width=100%]
[%header, cols="10,5,25"]
|===
|  Property  ^| Type | Description
| `clock-frequency` | Integer | Clock feeding the IP block in Hz.
3+| _A value of zero will preclude the ability to set the baud rate, or
to configure a disabled device._
| `reg-offset` | Integer | Offset to apply to the register map base address from the start of the registers.
| `reg-shift` | Integer | Quantity to shift the register offsets by.
| `reg-io-width` | Integer | The size (in bytes) of the register accesses that should be performed on the device.
3+| _1, 2, 4 or 8._
| `fifo-size` | Integer | The FIFO size (in bytes).
|===

