[[recipes]]
== Recipes

In this context, a recipe is a collection of firmware specification
requirements that hardware, firmware, and software providers can
implement to increase the likelihood that software written to the
recipe will run predictably on all conforming devices.

The BRS specification defines two recipes: BRS-I (for "Interoperable")
and BRS-B (for "Bespoke").

=== BRS-I Recipe

BRS-I is expected to be used by general-purpose compute devices such
as servers, desktops, laptops and other devices with industry
expectations on silicon vendor, OS and software ecosystem
interoperatbility.

<<recipe-brs-i-guidance, See additional guidance>>.

.BRS-I Recipe Overview
[width=100%]
[%header, cols="10,10,10,10,10,10"]
|===
| Profile | UEFI | ACPI | DT | SBI | SMBIOS
| >= RVA20 | >= 2.10 | >= 6.6 | N/A | >= 2.0 | >= 3.6.0
|===

=== BRS-B Recipe

BRS-B is intended for cases where only a minimal level of firmware
interaction is mandated, focusing primarily on the boot process.  The
BRS-B recipe is the simpler of the two BRS recipes.  It is expected to
be used by software that is tailored to specific devices.  Examples
include many types of mobile devices, devices with real time response
requirements, or embedded devices running rich operating systems with
custom distributions.

.BRS-B Recipe Overview
[width=100%]
[%header, cols="10,10,20,20,10,20"]
|===
| Profile | UEFI | ACPI | DT | SBI | SMBIOS
| >= RVA20 | EBBR cite:[EBBR] | optional, >= 6.6 | optional, >= v0.3 | >= 2.0 | optional, >= 3.6.0
|===
