[[sbi]]
== SBI Requirements

The supervisor binary interface (SBI) cite: [SBI] specification defines the interface
between the supervisor mode and the next higher privilege mode. This section
defines the mandatory SBI version and extensions implemented by the higher
privilege mode in order to be compatible with this specification.

[width=100%]
[%header, cols="5,25"]
|===
| ID#     ^| Requirement
| SBI_010  | The SBI implementation MUST conform to SBI v1.0.
| SBI_020  | The SBI implementation MUST implement the Hart State Management (HSM) extension.
2+| _HSM is used by an OS for starting up, stopping, suspending and querying the status of secondary harts. <<uefi-guidance-harts, See additional guidance>>._
| SBI_030  | The System Reset (SRST) extension MUST be implemented.
2+| _See <<uefi-resetsystem, UEFI requirements>> for additional notes on SRST use by a UEFI and OS._
|===

Certain requirements are conditional on the presence of RISC-V ISA extensions or system features.

[width=100%]
[%header, cols="5,25"]
|===
| ID#     ^| Requirement
| SBI_040  | The Timer (TIME) extension MUST be implemented, if the RISC-V "stimecmp / vstimecmp" Extension (Sstc) cite: [Sstc] is not available.
| SBI_050  | The S-Mode IPI (IPI) extension MUST be implemented, if the Incoming MSI Controller (IMSIC) cite: [Aia] is not available.
| SBI_060  | The RFENCE (RFNC) extension MUST be implemented, if the Incoming MSI Controller (IMSIC) cite: [Aia] is not available.
| SBI_070  | The Performance Monitoring (PMU) extension MUST be implemented, if the counter delegation-related ISA extensions (S*csrind cite: [Sscsrind], Smcdeleg cite: [Smcdeleg], Ssccfg cite: [Smcdeleg]) are not present.
2+| _NOTE: The PMU extension is currently being developed by the performance analysis TG cite: [PerfAnalysis]._
|===
