[[smbios]]
== SMBIOS Requirements

The System Management BIOS (SMBIOS) specification defines a standard format for presenting management information about an implentation, mostly focusing on hardware components.

This section defines the BRS-I mandatory and optional SMBIOS requirements
on top of cite:[SMBIOS], and is optional and recommended for BRS-B. Additional non-normative guidance may be found in the <<smbios-guidance, appendix>>.

.*SMBIOS structures in a conforming implementation*
[cols="1,3,2,4", width=95%, align="center", options="header"]
|===
| Type | SMBIOS Structure                          | Status      | Note
| 02   | Baseboard/Module Information              | Recommended |
| 03   | System Enclosure/Chassis                  | Recommended | Relaxes DMTF requirement.
| 08   | Port Connector Information                | Recommended | When physical ports present.
| 09   | System Slots                              | Conditional | Required when expansion slots present.
| 11   | OEM Strings                               | Recommended |
| 13   | BIOS Language Information                 | Recommended |
| 14   | Group Associations                        | Recommended | To describe associations between SMBIOS types.
| 38   | IPMI Device Information                   | Conditional | Required when IPMIv1.0 host interface present.
| 39   | System Power Supplies                     | Recommended | For servers.
| 41   | Onboard Devices Extended Information      | Recommended |
| 42   | Redfish Host Interface                    | Conditional | Required when Redfish host interface present.
| 43   | TPM Device                                | Conditional | Required when TPM present.
| 44   | Processor Additional Information | Required    |
| 45   | Firwmare Inventory Information            | Recommended |
| 46   | String Property                           | Recommended |
|===

=== Type 44 Processor-Specific Data

The processor-specific data structure fields are defined to follow the standard Processor-Specific Block fields (cite:[SMBIOS], Section 7.45.1).

The structure is defined in a manner consistent with the DMTF specification
language (cite:[SMBIOS]), and is valid for processors declared as
architecture 07h (64-bit RISC-V) only.

[cols="2,2,3,2,2,4", width=95%, align="center", options="header"]
|===
| Offset | Version | Name      | Length | Value   | Description
| 00h| 0100h|Revision|WORD|Varies|See <<smbios-psd-ver>>.
| 02h| 0100h| Hart ID| QWORD| Varies| The ID of this RISC-V Hart
| 0Ah| 0100h| Boot Hart| BYTE| Boolean| 1: This is boot hart to boot system +
0: This is not the boot hart
| 0Bh| 0100h| Machine Vendor ID | QWORD| Varies| The vendor ID of this
RISC-V Hart
| 13h| 0100h| Machine Architecture ID| QWORD| Varies| Base
microarchitecture of the hart. Value of 0 is possible to indicate the field is
not implemented. The combination of Machine Architecture ID and Machine Vendor
ID should uniquely identify the type of hart microarchitecture that is implemented.
| 1Bh| 0100h| Machine Implementation ID| QWORD| Varies| Unique encoding
of the version of the processor implementation. Value of 0 is possible to indicate
the field is not implemented. The Implementation value should reflect the design of
the RISC-V Hart.
| 23h| 0100h| Instruction set supported| DWORD| Bit-field | Bits [25:0]
encodes the presence of RISC-V standard extensions, which is equivalent to bits
[25:0] in RISC-V Machine ISA Register (**misa** CSR). Bits set to one mean the
certain extensions of instruction set are supported on this hart.
| 27h| 0100h| Privilege Level Supported| BYTE| Varies| The privilege levels
supported by this RISC-V Hart. +
Bit 0 Machine Mode +
BIT 1 Reserved +
BIT 2 Supervisor Mode +
Bit 3 User Mode +
BIT 6:4 Reserved +
BIT 7 Debug Mode
| 28h| 0100h| Machine Exception Trap Delegation Information| QWORD| Varies|
Bit set to one means the corresponding exception is delegated to supervisor execution
environment. Otherwise, supervisor execution environment must register the event
handler in Machine-Mode for the certain exceptions through environment call.
| 30h| 0100h| Machine Interrupt Trap Delegation Information| QWORD| Varies|
Bit set to one means the corresponding interrupt is delegated to supervisor execution
environment. Otherwise, supervisor execution environment must register the event
handler in Machine-Mode for the certain interrupts through environment.
| 38h| 0100h| The register width (XLEN)| BYTE| ENUM| The width of register
supported by this RISC-V Hart
| 39h| 0100h| Machine Mode native base integer ISA width (M-XLEN)| BYTE| ENUM|
The width (See below) of Machine Mode native base integer ISA supported by this RISC-V
Hart
| 3Ah| 0100h| Reserved| BYTE| ENUM| Placeholder for Hypervisor Mode
| 3Bh| 0100h| Supervisor Mode native base integer ISA width (S-XLEN)| BYTE| ENUM|
The width (See below) of Supervisor Mode native base integer ISA supported by this RISC-V
Hart
| 3Ch| 00100h| User Mode native base integer ISA width (U-XLEN)| BYTE| ENUM| The
width (See below) of the User Mode native base integer ISA supported by this RISC-V Hart
|===

[[smbios-psd-ver]]
=== Processor-Specific Data Structure Versioning

The processor-specific data structure begins with a revision field to allow for future extensibility in a backwards-compatible manner.

The minor revision is to be incremented anytime new fields are added in a backwards-compatible manner. The major revision is to be incremented on backwards-incompatible changes.

[cols="1,1,1,1,3", width=95%, align="center", options="header"]
|===
| Version | Bits 15:8+
Major revision
| Bits 7:0+
Minor revision
| Combined | Description
| v1.0 | 01h | 00h | 0100h | First BRS-defined definition
|===

=== Encoding of RISC-V Native Base Integer ISA Width

[cols="1,1", width=80%, align="center", options="header"]
|===
| Byte Value | Meaning
| 00h| Unsupported
| 01h| 32-bit
| 02h| 64-bit
| 03h| Unsupported
|===
