[[smbios]]
== SMBIOS Requirements

The System Management BIOS (SMBIOS) specification defines a standard format for presenting management information about an implentation, mostly focusing on hardware components.

This section defines the BRS-I mandatory and optional SMBIOS requirements
on top of cite:[SMBIOS], and is optional and recommended for BRS-B. Additional non-normative guidance may be found in the <<smbios-guidance, appendix>>.

.*SMBIOS structures in a conforming implementation*
[cols="1,3,2,4", width=95%, align="center", options="header"]
|===
| Type | SMBIOS Structure                          | Status      | Note
| 02   | Baseboard/Module Information              | Recommended |
| 03   | System Enclosure/Chassis                  | Recommended | Relaxes DMTF requirement.
| 08   | Port Connector Information                | Recommended | When physical ports present.
| 09   | System Slots                              | Conditional | Required when expansion slots present.
| 11   | OEM Strings                               | Recommended |
| 13   | BIOS Language Information                 | Recommended |
| 14   | Group Associations                        | Recommended | To describe associations between SMBIOS types.
| 38   | IPMI Device Information                   | Conditional | Required when IPMIv1.0 host interface present.
| 39   | System Power Supplies                     | Recommended | For servers.
| 41   | Onboard Devices Extended Information      | Recommended |
| 42   | Redfish Host Interface                    | Conditional | Required when Redfish host interface present.
| 43   | TPM Device                                | Conditional | Required when TPM present.
| 44   | Processor Additional Information | Required    |
| 45   | Firwmare Inventory Information            | Recommended |
| 46   | String Property                           | Recommended |
|===

=== Type 44 Processor-Specific Data

The following fields are defined to follow the standard processor-specific block fields (cite:[SMBIOS], Section 7.45.1).

The structure is defined in a manner consistent with the DMTF specification
language (cite:[SMBIOS]). In addition, DQWORD is taken to mean a 128-bit value.

The structure begins with a
a version field to allow for future extensibility in a backwards-compatible
manner. The version field is to be incremented any time fields are added.
The current version of the structure is 000Ah (v0.10).

[cols="2,2,3,2,2,4", width=95%, align="center", options="header"]
|===
| Offset | Version | Name      | Length | Value   | Description
| 00h|000Ah|Revision of RISC-V Processor-specific Block Structure|WORD|Varies|Bit 15:8 Major revision +
Bit 7:0 Minor revision +
The newer revision of RISC-V Processor-specific Block
Structure is backward compatible with older version of this structure.
| 02h| 000Ah| Hart ID| DQWORD| Varies| The ID of this RISC-V Hart
| 12h| 000Ah| Boot Hart| BYTE| Boolean| 1: This is boot hart to boot system +
0: This is not the boot hart
| 13h| 000Ah| Machine Vendor ID | DQWORD| Varies| The vendor ID of this
RISC-V Hart
| 23h| 000Ah| Machine Architecture ID| DQWORD| Varies| Base
microarchitecture of the hart. Value of 0 is possible to indicate the field is
not implemented. The combination of Machine Architecture ID and Machine Vendor
ID should uniquely identify the type of hart microarchitecture that is implemented.
| 33h| 000Ah| Machine Implementation ID| DQWORD| Varies| Unique encoding
of the version of the processor implementation. Value of 0 is possible to indicate
the field is not implemented. The Implementation value should reflect the design of
the RISC-V Hart.
| 43h| 000Ah| Instruction set supported| DWORD| Bit-field | Bits [25:0]
encodes the presence of RISC-V standard extensions, which is equivalent to bits
[25:0] in RISC-V Machine ISA Register (**misa** CSR). Bits set to one mean the
certain extensions of instruction set are supported on this hart.
| 47h| 000Ah| Privilege Level Supported| BYTE| Varies| The privilege levels
supported by this RISC-V Hart. +
Bit 0 Machine Mode +
BIT 1 Reserved +
BIT 2 Supervisor Mode +
Bit 3 User Mode +
BIT 6:4 Reserved +
BIT 7 Debug Mode
| 48H| 000Ah| Machine Exception Trap Delegation Information| DQWORD| Varies|
Bit set to one means the corresponding exception is delegated to supervisor execution
environment. Otherwise, supervisor execution environment must register the event
handler in Machine-Mode for the certain exceptions through environment call.
| 58H| 000Ah| Machine Interrupt Trap Delegation Information| DQWORD| Varies|
Bit set to one means the corresponding interrupt is delegated to supervisor execution
environment. Otherwise, supervisor execution environment must register the event
handler in Machine-Mode for the certain interrupts through environment.
| 68h| 000Ah| The register width (XLEN)| BYTE| ENUM| The width of register
supported by this RISC-V Hart
| 69h| 000Ah| Machine Mode native base integer ISA width (M-XLEN)| BYTE| ENUM|
The width (See below) of Machine Mode native base integer ISA supported by this RISC-V
Hart
| 6Ah| 000Ah| Reserved| BYTE| ENUM| Placeholder for Hypervisor Mode
| 6Bh| 000Ah| Supervisor Mode native base integer ISA width (S-XLEN)| BYTE| ENUM|
The width (See below) of Supervisor Mode native base integer ISA supported by this RISC-V
Hart
| 6Ch| 0000Ah| User Mode native base integer ISA width (U-XLEN)| BYTE| ENUM| The
width (See below) of the User Mode native base integer ISA supported by this RISC-V Hart
|===

=== Encoding of RISC-V Native Base Integer ISA Width

[cols="1,1", width=80%, align="center", options="header"]
|===
| Byte Value | Meaning
| 00h| Unsupported
| 01h| 32-bit
| 02h| 64-bit
| 03h| 128-bit
|===
