[[smbios]]
== SMBIOS Requirements

The System Management BIOS (SMBIOS) specification defines a standard format for presenting management information about an implentation, mostly focusing on hardware components.

This section defines the BRS-I mandatory and optional SMBIOS requirements
on top of cite:[SMBIOS], and is optional and recommended for BRS-B. Additional non-normative guidance may be found in the <<smbios-guidance, Firmware Implementation Guidance>> section.

[width=100%]
[%header, cols="5,25"]
|===
| ID#     ^| Requirement
| SMBIOS_010 | A Baseboard/Module Information (Type 02) structure SHOULD be implemented.
| SMBIOS_020 | A System Enclosure/Chassis (Type 03) structure SHOULD be implemented.
2+|_This relaxes the DMTF specification requirement._
| SMBIOS_030 | A Port Connector Information (Type 08) SHOULD be implemented.
| SMBIOS_040 | A System Slots (Type 09) structure MUST be implemented, when expansion slots are present.
| SMBIOS_050 | An OEM Strings (Type 11) structure SHOULD be implemented.
| SMBIOS_060 | A BIOS Language Information (Type 13) structure SHOULD be implemented.
| SMBIOS_070 | A Group Associations (Type 14) structure SHOULD be implemented.
| SMBIOS_080 | An IPMI Device Information (Type 38) structure MUST be implemented, when an IPMIv1.0 host interface is present.
| SMBIOS_090 | A System Power Supplies (Type 39) structure SHOULD be implemented.
| SMBIOS_100 | An Onboard Devices Extended Information (Type 41) structure SHOULD be implemented.
| SMBIOS_110 | A Redfish Host Interface (Type 42) structure MUST be implmented, when a Redfish host interface is present.
| SMBIOS_120 | A TPM Device (Type 43) structure MUST be implmented, when a TPM is present.
| SMBIOS_130 | A Processor Additional Information (Type 44) structure MUST be implemented.
2+| _See the <<smbios-type44, structure definitions below>>_.
| SMBIOS_140 | A Firwmare Inventory Information (Type 45) structure SHOULD be implemented.
| SMBIOS_150 | A String Property (Type 46) structure SHOULD be implemented.
|===

[[smbios-type44]]
=== Type 44 Processor-Specific Data

The processor-specific data structure fields are defined to follow the standard Processor-Specific Block fields (cite:[SMBIOS], Section 7.45.1).

The structure is defined in a manner consistent with the DMTF specification
language (cite:[SMBIOS]), and is valid for processors declared as
architecture 07h (64-bit RISC-V) only.

[cols="2,2,3,2,2,4", width=95%, align="center", options="header"]
|===
| Offset | Version | Name      | Length | Value   | Description
| 00h| 0100h|Revision|WORD|Varies|See <<smbios-psd-ver>>.
| 02h| 0100h| Hart ID| QWORD| Varies| The ID of this RISC-V hart
| 0Ah| 0100h| Machine Vendor ID | QWORD| Varies| The vendor ID of this
RISC-V hart
| 12h| 0100h| Machine Architecture ID| QWORD| Varies| Base
microarchitecture of the hart. Value of 0 is possible to indicate the field is
not implemented. The combination of Machine Architecture ID and Machine Vendor
ID should uniquely identify the type of hart microarchitecture that is implemented.
| 1Ah| 0100h| Machine Implementation ID| QWORD| Varies| Unique encoding
of the version of the processor implementation. Value of 0 is possible to indicate
the field is not implemented. The Implementation value should reflect the design of
the RISC-V processor and not the surrounding system.
|===

[[smbios-psd-ver]]
=== Processor-Specific Data Structure Versioning

The processor-specific data structure begins with a revision field to allow for future extensibility in a backwards-compatible manner.

The minor revision is to be incremented anytime new fields are added in a backwards-compatible manner. The major revision is to be incremented on backwards-incompatible changes.

[cols="1,1,1,1,3", width=95%, align="center", options="header"]
|===
| Version | Bits 15:8+
Major revision
| Bits 7:0+
Minor revision
| Combined | Description
| v1.0 | 01h | 00h | 0100h | First BRS-defined definition
|===
