[[uefi]]
== UEFI Requirements
=== UEFI Version
=== UEFI Compliance
=== UEFI Platform Initialization
The RISC-V Boot and Runtime Services Specification does not require following
the UEFI Platform Initialization Specification cite:[UEFI-PI].

Implementing the following elements is recommended:

* Security Architectural Protocol (EFI_SECURITY_ARCH_PROTOCOL)
* Security2 Architectural Protocol (EFI_SECURITY2_ARCH_PROTOCOL)footnote:[The
Security and Security2 Architectural Protocols are overridden by some
bootloaders (e.g. systemd-boot) to validate EFI binaries that cannot be
validated against the UEFI security database.]

=== UEFI System Environment and Configuration
==== Privilege Levels
===== UEFI Boot in HS-Mode
===== UEFI Boot in (V)S-Mode
==== System Volume Format
==== UEFI Image Format
===== UEFI Drivers
===== UEFI Applications
===== PE/COFF Images
==== Graphics Output (GOP) Protocol
==== Address Translation Support
=== UEFI Boot Services
==== Memory Map
==== UEFI Loaded Images
==== Configuration Tables
=== UEFI Runtime Services
==== Runtime Exception Level
==== Runtime Memory Map
==== Real-Time Clock (RTC)

[[uefi-resetsystem]]
==== UEFI Reset and Shutdown

The UEFI ResetSystem() runtime service must be implemented using the SBI System Reset (SRST) extension. The following table maps the UEFI RT and SRST call parameters:

[%autowidth]
|===
|ResetSystem() ResetType|sbi_system_reset type

|EfiResetShutdown
|0x00000000 (Shutdown)

|EfiResetCold
|0x00000001 (Cold reboot)

|EfiResetWarm
|0x00000002 (Warm reboot)

|EfiResetPlatformSpecific
|0xF0000000 - 0xFFFFFFFF (Vendor or platform specific reset type)
|===

The OS must call the ResetSystem() runtime service call to reset the system,
preferring this to SBI SRST or other platform-specific mechanisms. This
allows for UEFI implementations to perform any required platform tasks on the way out (e.g. servicing UpdateCapsule() or persisting non-volatile variables in some implementations).

==== Variable Services
=== UEFI Protocols
==== EFI TPM2 Protocol
The EFI TPM2 Protocol (EFI_TCG2_PROTOCOL) let's an UEFI software communicate
with a TPM v2 implementation.

If a system provides a TPM v2, the firmware should implement the
EFI TPM2 Protocol (EFI_TCG2_PROTOCOL) cite:[TcgEfiProt].

=== Firmware Update
