[[uefi]]
== UEFI Requirements

The Unified Extensible Firmware Interface (UEFI) specification describes the interface between the OS and the supervisor-mode firmware.

This section defines the BRS-I mandatory and optional UEFI requirements on top of cite:[UEFI], and is optional and recommended for BRS-B. Additional non-normative guidance may be found in the <<uefi-guidance, appendix>>.

A compliant system must:

* Implement a 64-bit UEFI firmware.
* Meet the 3rd Party UEFI Certificate Authority (CA) requirements on UEFI memory mitigations cite:[MSUefiCaRequirements].
* Meet the following UEFI memory map requirements:
** The default memory space attribute must be EFI_MEMORY_WB.
** Enable address translation.
** Only use EfiRuntimeServicesData memory type for describing any SMBIOS data structures.
* Declare a EFI_CONFORMANCE_PROFILES_UEFI_SPEC_GUID conformance profile, as the BRS requirements are a superset of UEFI cite:[UEFI] (Section 2.6).
* Declare EFI_CONFORMANCE_PROFILE_BRS_1_0_SPEC_GUID conformance profile ({ 0x05453310, 0x0545, 0x0545, { 0x05, 0x45, 0x33, 0x05, 0x45, 0x33, 0x05, 0x45 }}).

The BRS does not require complying with the UEFI Platform Initialization Specification cite:[UEFI-PI].

Only a system fully compliant to the requirements in this section
may declare the EFI_CONFORMANCE_PROFILE_BRS_1_0_SPEC_GUID conformance profile.

=== Security Requirements

Systems implementing secure boot must support the following UEFI Platform Initialization Specification cite:[UEFI-PI] protocols:

* EFI_SECURITY_ARCH_PROTOCOL
* EFI_SECURITY2_ARCH_PROTOCOL

Systems implementing a TPM must implement the TCG
EFI Protocol Specification cite:[TcgEfiPlat].

<<uefi-guidance-security, See additional guidance>>.

=== PCIe

Systems implementing PCIe must always initialize all root complex
hardware and perform resource assignment for all endpoints and usable
hotplug-capable switches in the system, even in a "rapid boot"
scenario from a non-PCIe boot device. This is a stronger requirement
than the PCI Firmware Specification firmware/OS device hand-off state
(cite:[PCIFW] Section 3.5).

<<uefi-guidance-pcie, See additional guidance>>.

=== UEFI Runtime Services

[[uefi-rtc]]
==== Real-Time Clock (RTC)

The RTC is usually exposed via the UEFI GetTime and SetTime runtime services.

===== Systems without an RTC

* GetTime must be implemented (e.g. in terms of CPU cycle counter).
* SetTime must return EFI_UNSUPPORTED, and be appropriately described in EFI_RT_PROPERTIES_TABLE.

===== Systems with an RTC

Where the RTC is on an OS-managed bus (e.g. I2C, subject to arbiration issues due to access to the bus by the OS):

* The ACPI Time and Alarm Device <<acpi-tad, must be implemented>>.
* GetTime and SetTime must return EFI_UNSUPPORTED, when called after the UEFI boot services have been exited.
* GetTime and SetTime must be appropriately described in EFI_RT_PROPERTIES_TABLE.

[[uefi-resetsystem]]
==== UEFI Reset and Shutdown

The UEFI ResetSystem() runtime service must be implemented using the SBI System Reset (SRST) extension. The following table maps the UEFI RT and SRST call parameters:

[%autowidth]
|===
|ResetSystem() ResetType|sbi_system_reset type

|EfiResetShutdown
|0x00000000 (Shutdown)

|EfiResetCold
|0x00000001 (Cold reboot)

|EfiResetWarm
|0x00000002 (Warm reboot)

|EfiResetPlatformSpecific
|0xF0000000 - 0xFFFFFFFF (Vendor or platform specific reset type)
|===

The OS must call the ResetSystem() runtime service call to reset the system,
preferring this to SBI SRST or other platform-specific mechanisms. This
allows for UEFI implementations to perform any required platform tasks on the way out (e.g. servicing UpdateCapsule() or persisting non-volatile variables in some implementations).

==== Variable Services

* Non-volatile UEFI variables must persist across EFI ResetSystem() calls.
* The UEFI Runtime Services must be able to update the variables directly without the aid of the operating system.

=== Firmware Update

Systems with updatable firmware must implement either an in-band (firmware on hart updates itself) or an out-of-band firmware update mechanism (for example, by a Base Management Controller, BMC)).

In-band firmware updates must be implemented in one of two ways:

* UpdateCapsule() UEFI runtime service (cite:[UEFI] Section 8.5.3).
** Firmware must accept updates in the "Firmware Management Protocol Data Capsule Structure" format as described in "Delivering Capsules Containing Updates to Firmware Management Protocol" cite:[UEFI] (Section 23.3).
** Must provide an ESRT cite:[UEFI] (Section 23.4) describing every firmware image that is updated in-band.
** UpdateCapsule() is allowed to return EFI_UNSUPPORTED, when called after the UEFI boot services have been exited. <<uefi-guidance-firmware-update, See additional guidance>>.
* Delivery of Capsules via file on Mass Storage Device (cite:[UEFI] Section 8.5.5).

