ACPI information is structured as tables with the address of the root of these
tables known as Root System Description Table (RSDP) passed to the OS
via a EFI_ACPI_20_TABLE_GUID configuration table in the UEFI firmware.
The Operating System uses this address to locate all other ACPI tables.

Certain implementations may make use of the RISC-V Functional Fixed hardware Specification cite:[FFH].

[[acpi-guidance-64bit-clean]]
==== 64-bits Clean

ACPI started as a specification for 32-bit systems,
so certain tables with physical address pointers (e.g. RSDP, FADT) allow for reporting
either 32-bit or 64-bit values using different fields. For the sake of simplicity
and consistency, the BRS disallows the use 32-bit address fields in such structures
and disallows the use of 32-bit only structures (thus, RSDT must not be implemented,
as the XSDT is a direct replacement). Thus, the ACPI tables are allowed to be
located in any part of the physical address space.

[[acpi-guidance-hw-reduced]]
==== Hardware-Reduced ACPI

Compliant RISC-V systems only implement the HW-Reduced ACPI Model cite:[ACPI] (Section 4.1).
This means the hardware portion of cite:[ACPI] (Section 4) is not required or
supported. All functionality is instead provided through equivalent
software-defined interfaces and the complexity in supporting ACPI is reduced.

==== Table Guidance
<<acpi-guidance-tab-min>> summarizes the minimum set of structures
that must exist to support basic booting of RISC-V system with ACPI
support. <<acpi-guidance-tab-opt>> lists additional possible ACPI
tables based on the optional features that can be supported. The
latter is not meant to be exhaustive and mostly focuses on tables that
have specific guidance or that are expected to be frequently
implemented.

.*Minimum required ACPI System Description Tables*
[[acpi-guidance-tab-min]]
[cols="3,2,2", width=95%, align="center", options="header"]
|===
|ACPI Table                                    |ACPI Section|Note
|Root System Description Pointer (RSDP)        |5.2.5      | See <<acpi-64bit-clean, high-level requirements>>.
|Extended System Description Table (XSDT)      |5.2.8      | Contains pointers to other tables.
|Fixed ACPI Description Table (FADT)           |5.2.9      | See <<acpi-hw-reduced>>, <<acpi-guidance-hw-reduced>> and <<acpi-guidance-fadt, the notes below>>.
|Differentiated System Description Table (DSDT)|5.2.11.1   | See <<acpi-aml>> and <<acpi-guidance-aml, the notes below>>.
|Multiple APIC Description Table (MADT)        |5.2.12     | See <<acpi-guidance-madt, the notes below>>
|RISC-V Hart Capabilities Table (RHCT)         |New        | Communicates
information about certain capabilities like ISA string, cache and MMU info.
|Processor Properties Topology Table (PPTT)    |5.2.29     | See <<acpi-pptt>>
|===

// Add RIMT for IOMMU here.

.*Additional ACPI System Description Tables based on feature support.*
[[acpi-guidance-tab-opt]]
[cols="3,2,2", width=95%, align="center", options="header"]
|===
|ACPI Table                                    |ACPI Section  |Note
|Memory-mapped Configuration space (MCFG)      |cite:[PCIFW]  |See <<acpi-mcfg>> and <<acpi-guidance-pcie, the notes below>>
|Secondary System Description Table (SSDT)     |5.2.11.2      |See <<acpi-aml>> and <<acpi-guidance-aml, the notes below>>.
|Serial Port Console Redirection (SPCR)        |cite:[SPCR]   |See <<acpi-spcr>> and <<acpi-guidance-spcr, the notes below>>
|ACPI Table for TPM 2.0 (TPM2)                 |cite:[TcgAcpi]|If the system supports TPM 2.0
|System Resource Affinity Table (SRAT)         |5.2.16        |If the system supports NUMA
|System Locality Information Table (SLIT)      |5.2.17        |If the system supports NUMA
|Boot Error Record Table (BERT)                |18.3.1        |If APEI is supported
|Error Injection Table (EINJ)                  |18.6.1        |If APEI is supported
|Error Record Serialization Table (ERST)       |18.5          |If APEI is supported
|Hardware Error Source Table (HEST)            |18.3.2        |If APEI is supported
|===

[[acpi-guidance-aml]]
==== DSDT and SSDTs

The ACPI name space describes devices which cannot be enumerated by any other standard ways. These typically include SoC embedded memory-mapped I/O devices, such as UARTs, <<acpi-guidance-pcie, PCIe>> or CXL root complexes, GPIO controllers, etc.

It's an implementation choice if the ACPI name space is defined solely with a DSDT or with any additional SSDTs. For example, a UEFI implementation
may choose to use SSDTs to:

* describe devices that vary across SoC SKUs, revisions or variants.
* describe devices, where the backing AML is generated or patched at boot time.

// Provide guidance here for converting existing device tree node definitions to ACPI.

// Provide guidance here for describing NS16550-compatible UARTs.

// Provide guidance here for PCIe RCs, perhaps leverage some of https://www.infradead.org/~mchehab/rst_conversion/PCI/acpi-info.html

[[acpi-guidance-fadt]]
==== FADT

cite:[ACPI] (Section 5.2.9) provides guidance on filling the
Fixed ACPI Description Table for HW-reduced ACPI.

Don't forget to select an appropriate Preferred PM Profile.

[[acpi-guidance-madt]]
==== MADT

RINTC (per-hart) structures are mandatory. Depending on the interrupt controller implemented by the system, the MADT will also contain either PLIC or IMSIC/APLIC structures.

Entry ordering can be correlated with initialization order by an OS, but
should not be taken to reflect affinity in resource sharing,
e.g. sockets, caches, etc. RINTC hart ID and ACPI Processor UID should
not be decoded in a system-specific manner to divine CPU topology.
The PPTT Processor Properties Topology Table (PPTT) is to be used to
describe affinities.

[[acpi-guidance-gsi-namespace]]
==== PLIC/APLIC as namespace devices
The devices which have wired interrupts (GSI), should provide the
dependency on the appropriate interrupt controller similar to below
example with PLIC.


 Scope (\_SB)
 {
    Device (IC00)
    {
        Name (_HID, "RSCV0001") // _HID: Hardware ID
        Name (_UID, Zero)  // _UID: Unique ID
        Method(_GSB) {
            Return (0x10) // Global System Interrupt Base for this PLIC starts at 16
       }
    }
    Device (DEV1)
    { 
      ...
      Name (_DEP, Package() {\_SB.IC00})
      Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
      {   
          Memory32Fixed (ReadWrite,
            0x10010000,         // Address Base.
            0x00010000,         // Address Length
            )
          Interrupt (ResourceConsumer, Level, ActiveHigh, Exclusive, ,,)
          { 
            0x10,
          }
      })
    }
 }

[[acpi-guidance-pcie]]
==== PCIe

On some architectures, it became an industry accepted norm to describe PCIe implementations not compliant to the PCI Firmware Specification cite:[PCIFW]
using specification-defined ACPI tables and objects. RISC-V systems compliant to the BRS must only expose ECAM-compatible implementations using the
MCFG and the standard AML Hardware ID (HID) PNP0A08 and Compatible ID (CID) PNP0A03, and must not rely on ACPI table header information or other out-of-band
means of detecting quirked behavior.

Some minor incompatibilities, such as incorrect CFG0 filtering, broken BARs/capabilities for RCs, embedded switches/bridges
or embedded endpoints can be handled by emulating ECAM accesses in privileged firmware (e.g. M-mode) or similar facilities (e.g. a hypervisor).

Non-compliant implementations must be exposed using vendor-specific mechanisms (e.g. AML object with custom HID, custom vendor-specific ACPI table if necessary).
In cases where such PCIe implementations are only used to expose a fixed non-removable device (e.g. USB host controller or NVMe), the device could be exposed via
a DSDT/SSDT MMIO device object without making the OS aware of the underlying PCIe connection.

// Provide guidance here on AML object used, including interrupt routing, why I/O space is not included.

[[acpi-guidance-spcr]]
==== SPCR

Early serial console can be implemented using either an NS16550 UART (SPCR Interface Type 0x12) or
SBI console (SPCR Interface Type 0x15). When SPCR describes SBI console, the OS must use
the SBI Probe extension (FID #3) to detect the appropriate facilities, e.g. the Debug Console Extension
(DBCN) or the deprecated legacy console EIDs.

The new Precise Baud Rate field, introduced in cite:[SPCR] rev. 4, allows describing rates faster
than 115200 baud for NS16550-compatible UARTS.

Hardware not capable of interrupt-driven operation and SBI console should be described with
Interrupt Type 0 and Global System Interrupt 0.
