[[recipe-brs-i-guidance]]
===== BRS-I Recipe Guidance

Systems compliant to BRS-I can successfully boot an existing generic
operating system image without system-specific customizations, yet
this might result in an unoptimized experience and non-functioning
I/O devices until further software updates are activated.

The best analogy would be a typical Intel Architecture motherboard from
the early 2000s: you could install an OS on it, but the built-in graphics
might be low-resolution and the sound, built-in network port or power
management might not work out of the box. You could subsequently load
the right drivers from the media coming with the board or fetch newest
ones using a well-supported network adapter.

Heterogeneous performance harts (e.g. mix of "performance" and "efficiency"
harts) is a great example of a feature outside the current scope of BRS-I,
yet with potential for adverse effects to a generic operating system
written against the BRS-I spec. Such a feature does not have a standard
way of being detected by an OS, leading to scheduling anomalies in
operating systems that are not specially adapted. Consider two identical
threads that, unbeknownst to the OS, get scheduled on harts with different
performance characteristics. This might see dramatic difference in forward
progress being made, with unexpected delays, timeouts or even crashes
posible. Worse, there could be little to no system messages pointing to
the cause of such behavior. Thus, such a feature would need to be made
*opt-in* for BRS-I compliance. This could be done implicitly via loading
of system-specific drivers, or explicitly via firmware setup and
configuration utilities. The actual meaning of the default (compatible to
BRS-I) configuration would be highly specific to the vendor. In this example,
it could capping all harts at the same performance level, or it could mean
disabling efficiency harts.

[[recipe-brs-m-guidance]]
===== BRS-M Recipe Guidance

In contrast to BRS-I and BRS-B, BRS-M has no implementation of UEFI related
services. Non-UEFI firmware, such as *coreboot*, can also supports boot well.
Although non-UEFI firmware does not support UEFI interface, it can also
provide ACPI, SMBIOS and SBI services. ACPI and SMBIOS can be passed through
DT.

The introduction of coreboot can refer to https://www.coreboot.org/[coreboot].
This solution is the startup mode for coreboot plus payload. coreboot does the
basic and necessary hardware initialization, where ACPI and SMBIOS tables are
created, and then loads and executes payload, which completes the boot and
additional functions. linuxboot is a common payload.
