UEFI implementations run in 64-bit S-Mode, VS-Mode or HS-Mode,
depending on whether virtualization is supported or used.

==== Privilege Levels

Different portions of system firmware might target a specific
privilege level. In contrast, UEFI drivers, OS loaders and
pre-boot applications need to operate in supervisor mode (either
(V)S-Mode or HS-Mode), because they are UEFI-compliant executable
images.

As an implementation choice, a UEFI firmware implementation may
start execution in M-Mode. However it must switch to supervisor
mode as part of initializing boot and runtime services for UEFI
drivers and applications.

[[uefi-guidance-firmware-update]]
==== Firmware Update

`UpdateCapsule()` is only required before `ExitBootServices()` is called.
The `UpdateCapsule()` implementation is expected to be suitable for use by generic firmware update services like fwupd and Windows Update. Both fwupd and Windows Update read the ESRT table to determine what firmware can be updated and use an EFI helper application to call `UpdateCapsule()` before `ExitBootServices()` is called.

[[uefi-guidance-pcie]]
==== PCIe

Every implementation of the `EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL` provides the
correct `Address Translation Offset` field to translate between the hart
MMIO and bus addresses.

`EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL_CONFIGURATION` structures report resources
produced by the PCIe root bridges, not resources consumed by their
register maps. In the cases where there are unpopulated PCIe slots
behind a root bridge, `EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL_CONFIGURATION`
reports valid resources assigned (e.g. for hot plug), or reports no
resources assigned.

Firmware MUST always initialize PCIe root complexes, even if booting from non-PCIe devices,
and should not assume the OS knows how to configure root complex hardware (including,
for example, inbound and outbound address translation windows). In fact, ECAM-compatible
PCIe segments are assumed by operating systems to just work as per their hardware
descriptions in ACPI and DT. Furthermore, firmware MUST perform BAR resource assignment,
bridge bus number and window assignments and other reasonable device setting configuration
(e.g. Max Payload Size) and not assume operating systems to be capable of full PCIe
resource configuration, or to expect full reconfiguration to be necessary.

[[uefi-guidance-rt]]
==== UEFI Runtime Services

Systems without an RTC and with an equivalent alternate source for current time,
that is not trivially accessible from a UEFI implementation after the
UEFI boot services are shut down (e.g. network time), can implement `GetTime()`
using the `time` CSR. The time, of course, needs to be synchronized
before the boot services are shut down.